---

# No need to gather facts. See: https://medium.com/@abhijeet.kamble619/10-things-you-should-start-using-in-your-ansible-playbook-808daff76b65
- hosts: all
  gather_facts: False
  any_errors_fatal: True
  # gather_subset: network, ohai, facter, hardware, virtual

- name: Apply common configuration to all nodes
  hosts: all
  remote_user: root
  roles:
    - common

- name: Apply common configuration to jenkins hosts
  hosts: jenkinshosts
  remote_user: root
  roles:
    - jenkinshosts

- name: apply common configuration to jenkinsserver hosts
  hosts: jenkins
  remote_user: root
  roles:
    - jenkinsserver

- name: apply common configuration to desktops
  hosts: desktop
  remote_user: root
  roles:
    - desktop

- name: Apply common configuration to jira hosts
  hosts: jira
  remote_user: root
  roles:
    - jira

- name: Apply common configuration to jumpoff hosts
  hosts: jumpoff
  remote_user: root
  roles:
    - jumpoff
