---
# This playbook contains common plays that will be run on all nodes.
# Set up local storage
- name: Creates media directory 1
  file:
    path: /media/storage_1
    state: directory
    owner: imiell
    group: imiell
    mode: 0775
- name: Creates media directory 2
  file:
    path: /media/storage_2
    state: directory
    owner: imiell
    group: imiell
    mode: 0775
- name: Creates space folder
  file:
    path: /space
    state: directory
    owner: imiell
    group: imiell
    mode: 0775
- name: Creates git folder
  file:
    path: /space/git
    state: directory
    owner: imiell
    group: imiell
    mode: 0775
- name: Creates jenkins cache folder
  file:
    path: /space/jenkins_cache
    state: directory
    owner: imiell
    group: imiell
    mode: 0775



- apt: name=apt-transport-https state=present
- apt: name=ca-certificates state=present
- apt: name=curl state=present
- apt: name=software-properties-common state=present

- apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- shell: 'add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"'
- apt: name=docker-ce state=present

# Adding the groups to an existing user doesn't delete the groups already assigned.
- name: Add the user 'imiell' with a specific uid and groups
  user:
    name: imiell
    comment: Ian Miell
    groups: sudo,docker

# TODO: ensure /space/git/ and work repo is there.

- name: Generate /etc/ssh/ RSA host key
  command: ssh-keygen -q -t rsa -f /home/imiell/.ssh/id_rsa -C "" -N "" creates=/etc/ssh/ssh_host_rsa_key
  tags: work

- git:
    repo: ssh://meirionconsulting.com/var/cache/git/work
    dest: /space/git/work
  tags: work


# Let's encrypt
- name: Add let's encrypt repo
  apt_repository:
    repo:  ppa:certbot/certbot
    state: present
- name: Install python-certbot-apache
  apt: name=python-certbot-apache state=present

# GRUB customizer
- name: Add grub-customizer repo
  apt_repository:
    repo: ppa:danielrichter2007/grub-customizer
    state: present
- name: Install grub-customizer
  apt: name=grub-customizer state=present


# Sysdig installation
- name: Add sysdig apt key
  apt_key:
    url: https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public

- name: Get sysdig sources list
  get_url:
    url: https://s3.amazonaws.com/download.draios.com/stable/deb/draios.list
    dest: /etc/apt/sources.list.d/draios.list
    mode: 0640

- name: Install sysdig
  apt: name=sysdig state=present
  tags: sysdig
- name: Install falco
  apt: name=falco state=present
  tags: sysdig, falco

# youtube-dl
- name: Get youtube-dl
  get_url:
    url: https://yt-dl.org/latest/youtube-dl
    dest: /usr/local/bin/youtube-dl
    mode: 0755


# Dotfiles
- git:
    repo: 'https://github.com/ianmiell/dotfiles.git'
    dest: /home/imiell/.dotfiles

# Dotfiles
- git:
    repo: 'https://github.com/ianmiell/dotfiles.git'
    dest: /home/imiell/.dotfiles

# Power management
- lineinfile:
    path: /etc/systemd/logind.conf
    regexp: '^HandleLidSwitch.*'
    line: 'HandleLidSwitch=ignore'
    state: present
  notify: restart systemd-logind


- lineinfile:
    path: /etc/UPower/UPower.conf
    regexp: 'IgnoreLid=.*'
    line: 'IgnoreLid=true'
    state: present
  notify: restart upower


# To diagnose crashes
- name: Install crash
  apt: name=crash state=present

# For gems
- name: Install rubyd-ev
  apt: name=ruby-dev state=present
- name: Install libtool
  apt: name=libtool state=present
- name: Install autoconf
  apt: name=autoconf state=present


# Required for some dep issues with python3
- apt: name=sosreport state=present

# Maven
- apt: name=maven state=present

# Sec standards
- apt: name=auditd state=present
- apt: name=fail2ban state=present

# Disk usage analysis
- apt: name=xdiskusage state=present
- apt: name=ncdu state=present
# IPTables state viewer
- apt: name=iptstate state=present
# Text-only browser
- apt: name=links state=present
# DNS
- apt: name=ldnsutils state=present
- apt: name=libldns2 state=present

- apt: name=bpython state=present
- apt: name=vim state=present
- apt: name=run-one state=present
- apt: name=python-pip state=present
- apt: name=socat state=present
- apt: name=etherwake state=present
- apt: name=openssh-server state=present
- apt: name=apache2 state=present
- apt: name=tmux state=present
- apt: name=alien state=present
- apt: name=git state=present
- apt: name=git-extras state=present
- apt: name=ntp state=present
- apt: name=moreutils state=present
- apt: name=npm state=present
- apt: name=openjdk-8-jre state=present
- apt: name=asciidoc state=present
- apt: name=asciidoctor state=present
- apt: name=awscli state=present
- apt: name=python3-pip state=present
- apt: name=jq state=present
- apt: name=fslint state=present
- apt: name=pylint state=present
- apt: name=apt-file state=present
- apt: name=shellcheck state=present
- apt: name=sqlite3 state=present
- apt: name=golang-go state=present
- apt: name=gnuplot state=present
- apt: name=ioping state=present
- apt: name=sysstat state=present
- apt: name=fdupes state=present
- apt: name=html2text state=present
- apt: name=software-properties-common state=present
- apt: name=curl state=present
- apt: name=apt-transport-https state=present
- apt: name=ca-certificates state=present
- apt: name=pandoc state=present
- apt: name=htop state=present
- apt: name=nmap state=present
- apt: name=tasksel state=present
- apt: name=php state=present
- apt: name=qemu state=present
- apt: name=qemu-kvm state=present

- lineinfile:
    path: /etc/default/sysstat
    regexp: '^ENABLED=.*'
    line: 'ENABLED=true'
    state: present
  notify: restart sysstat

# Set up local storage                                                                                                                                                         
- git:
    repo: 'https://github.com/ianmiell/dotfiles.git'
    dest: /home/imiell/.dotfiles
  become: yes
  become_user: imiell

- pip:
    name: requests
    state: latest

- pip:
    name: coverage
    state: latest

- pip:
    name: python-twitter
    state: latest

- pip:
    name: setuptools
    state: latest

- pip:
    name: twine
    state: latest

- pip:
    name: butterfly
    state: latest

- pip:
    name: shutit
    state: latest

- pip:
    name: awsscout2
    state: latest


- apt: name=dnsmasq state=present

# https://unix.stackexchange.com/a/304798/93547
- name: ensure dnsmasq directory exists
  file:
    path: /etc/systemd/system/dnsmasq.service.d
    recurse: yes
    state: directory
  tags: dnsmasq

- template:
    src: templates/etc/systemd/system/dnsmasq.service.d/resolved-fix.conf
    dest: /etc/systemd/system/dnsmasq.service.d/resolved-fix.conf
  notify: restart dnsmasq
  tags: dnsmasq



# gems: https://docs.ansible.com/ansible/latest/modules/gem_module.html?highlight=gem
- gem:
    name: inspec
    state: latest
- gem:
    name: asciidoctor-pdf
    state: latest
- gem:
    name: asciidoctor-reveal-js
    state: latest
- gem:
    name: coderay
    state: latest
- gem:
    name: pygments
    state: latest
- gem:
    name: tilt
    state: latest
- gem:
    name: slim
    state: latest
