---
# This playbook contains common plays that will be run on all nodes.

- name: Install ntp
  apt: name=ntp state=present
  tags: ntp

# Required for some dep issues with python3
- name: install sosreport
  apt: name=sosreport state=present
  tags: sosreport

# Adding the groups to an existing user doesn't delete the groups already assigned.
- name: Add the user 'imiell' with a specific uid and groups
  user:
    name: imiell
    comment: Ian Miell
    groups: sudo,docker

# Let's encrypt
- name: Add let's encrypt repo
  apt_key:
    ppa: certbot/certbot
- name: Install python-certbot-apache
  apt: name=python-certbot-apache state=present

# GRUB customizer
- name: Add grub-customizer repo
  apt_key:
    ppa: danielrickter2007/grub-customizer
- name: Install grub-customizer
  apt: name=grub-customizer state=present


# Sysdig installation
- name: Add sysdig apt key
  apt_key:
    url: https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public

- name: Get sysdig sources list
  get_url:
    url: https://s3.amazonaws.com/download.draios.com/stable/deb/draios.list
    dest: /etc/apt/sources.list.d/draios.list
    mode: 0640

- name: Install sysdig
  apt: name=sysdig state=present
  tags: sysdig
- name: Install falco
  apt: name=falco state=present
  tags: sysdig, falco

# Dotfiles
- git:
    repo: 'https://github.com/ianmiell/dotfiles.git'
    dest: /home/imiell/.dotfiles

# Power management
- lineinfile:
    path: /etc/systemd/logind.conf
    regexp: '^HandleLidSwitch.*'
    line: 'HandleLidSwitch=ignore'
    state: present
  notify: restart systemd-logind

# To diagnose crashes
- name: Install crash
  apt: name=crash state=present

# For gems
- name: Install rubyd-ev
  apt: name=ruby-dev state=present
- name: Install libtool
  apt: name=libtool state=present
- name: Install autoconf
  apt: name=autoconf state=present

# Maven
- name: Install maven
  apt: name=maven state=present

# Sec standards
- name: Install auditd
  apt: name=auditd state=present
- name: Install fail2ban
  apt: name=fail2ban state=present

# Disk usage analysis
- name: Install xdiskusage
  apt: name=xdiskusage state=present
- name: Install ncdu
  apt: name=ncdu state=present

# IPTables state viewer
- name: Install iptstate
  apt: name=iptstate state=present

# Text-only browser
- name: Install links
  apt: name=links state=present

# DNS
- name: Install ldnsutils
  apt: name=ldnsutils state=present
- name: Install libldns2
  apt: name=libldns2 state=present





#- name: Configure ntp file
#  template: src=ntp.conf.j2 dest=/etc/ntp.conf
#  tags: ntp
#  notify: restart ntp
#
#- name: Start the ntp service
#  service: name=ntpd state=started enabled=yes
#  tags: ntp

# TODO: what is this?
#- name: test to see if selinux is running
#  command: getenforce
#  register: sestatus
#  changed_when: false
